# Generated by Django 6.1.1 on 2026-09-27 16:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. Used as the login identifier.', max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(help_text="Required. The user's full name.", max_length=150, verbose_name='full name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('OWNER', 'Store Owner'), ('MANAGER', 'Manager'), ('SHIPPER', 'Shipper')], help_text='The role of the user inside the store. Platform superusers have no store role.', max_length=20, null=True, verbose_name='role')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can access the Django admin.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account is active.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('store', models.ForeignKey(blank=True, help_text='The store for this user. Only platform superusers can have no store.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='stores.store')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['store', 'role', 'is_active'], name='user_store_role_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_superuser', True), ('role__isnull', True), ('store__isnull', True)), models.Q(('is_superuser', False), ('role__isnull', False), ('store__isnull', False)), _connector='OR'), name='user_store_role_scope_valid'), models.CheckConstraint(condition=models.Q(('is_superuser', False), ('is_staff', True), _connector='OR'), name='superuser_must_be_staff')],
            },
        ),
    ]
