# Generated by Django 6.1.1 on 2026-09-27 16:29

import django.core.validators
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the store.', primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'A store with this name already exists.'}, help_text='The public name of the business.', max_length=200, verbose_name='store name')),
                ('description', models.TextField(blank=True, default='', help_text='Short information about the business and its services.', verbose_name='description')),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail'), ('CLOTHING_AND_FASHION', 'Clothing and Fashion'), ('SPORTS_AND_FITNESS', 'Sports and Fitness'), ('RESTAURANT', 'Restaurant'), ('FOOD_AND_BEVERAGE', 'Food and Beverage'), ('ELECTRONICS', 'Electronics'), ('HOME_AND_FURNITURE', 'Home and Furniture'), ('BEAUTY_AND_PERSONAL_CARE', 'Beauty and Personal Care'), ('HEALTHCARE', 'Healthcare'), ('PHARMACY', 'Pharmacy'), ('SOFTWARE_AND_TECH', 'Software and Technology'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('SERVICE_BUSINESS', 'Service Business'), ('FREELANCER', 'Freelancer'), ('EDUCATION', 'Education and Training'), ('REAL_ESTATE', 'Real Estate'), ('AUTOMOTIVE', 'Automotive'), ('TRAVEL_AND_HOSPITALITY', 'Travel and Hospitality'), ('WHOLESALE', 'Wholesale'), ('MANUFACTURING', 'Manufacturing'), ('CONSTRUCTION', 'Construction'), ('LOGISTICS_AND_DELIVERY', 'Logistics and Delivery'), ('EVENTS_AND_ENTERTAINMENT', 'Events and Entertainment'), ('MEDIA_AND_CONTENT', 'Media and Content'), ('PETS_AND_ANIMALS', 'Pets and Animals'), ('AGRICULTURE', 'Agriculture'), ('COMPANY', 'Company'), ('OTHER', 'Other')], default='OTHER', help_text='The main type of the business.', max_length=30, verbose_name='business type')),
                ('whatsapp_number', models.CharField(error_messages={'unique': 'A store with this WhatsApp number already exists.'}, help_text='The WhatsApp number used by this business in international format.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid WhatsApp number in international format.', regex='^\\+[1-9]\\d{8,14}$')], verbose_name='WhatsApp number')),
                ('status', models.CharField(choices=[('PENDING_ACTIVATION', 'Pending Activation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='PENDING_ACTIVATION', help_text='The current status of the store.', max_length=30, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='store_name_case_insensitive_unique')],
            },
        ),
    ]
